### ISSUE TITLE
`torch.outer` is not yet present in pytorch

### ISSUE THREAD

**Issue by mariogeiger** [xitorch/xitorch#1]
Dear developer, 

You are using a function `torch.outer` that is not available in `pytorch 1.6.0`.

**Comment by xitorch-developer** [comment]
Hi @mariogeiger, thanks for the issue. This repo is just for anonymizing for paper submission and mirrorring the actual repo. Anyway, I have updated this repo to fix this bug and to include more algorithm implementations.
