### ISSUE TITLE
Incompatibility with pytorch 1.10

### ISSUE THREAD

**Issue by mfkasim1** [xitorch/xitorch#11]
**Describe the bug**
Upgrading the pytorch to 1.10 makes some of the test fails (while it succeeds in 1.9 & 1.8).

**To Reproduce**
1. Install xitorch with pytorch 1.10
2. Run the test (`cd xitorch/_tests/; pytest`)
3. See error

```
FAILED test_optimize.py::test_equil[dtype0-device0-DummyModule] - torch.autograd.gradcheck.GradcheckError: Jacobian m...
FAILED test_optimize.py::test_equil[dtype1-device1-DummyNNModule] - torch.autograd.gradcheck.GradcheckError: Jacobian...
FAILED test_optimize.py::test_equil[dtype2-device2-DummyModule] - torch.autograd.gradcheck.GradcheckError: While cons...
```

**Expected behavior**
Seamless transition to 1.10

**Systems:**
 - OS: Ubuntu 20.04 WSL
 - Python version: 3.8.5
 - PyTorch version: 1.10
 - xitorch version: 0.4.0.dev0+47631ef

**Additional context**
-

**Comment by mfkasim1** [comment]
Temporarily fixed by setting the backward algorithm in those test into `"exactsolve"`. Setting it to `"cg"` will still produce an error.

**Comment by KarimAED** [comment]
Is this still an issue? Checking through existing problems in context of trying to revive XiTorch a little.

**Comment by mfkasim1** [comment]
It's compatible now with 2.3
