### ISSUE TITLE
Complex hermitian matrices not recognized as hermitian.

### ISSUE THREAD

**Issue by JonathanSchmidt1** [xitorch/xitorch#8]
**Describe the bug**
We were using xitorch with complex hermitian matrices and noticed that it would not check for hermiticity but for symmetry, therefore it raised a wrong error message.
is_hermitian = torch.allclose(mat, mat.transpose(-2, -1))
Of course this can be fixed by adding a .conj() (tested it error message disappears), however I am not sure if anything else in the code relies on the matrix being real. 

**To Reproduce**
```python
import torch, xitorch
from xitorch import linalg 

a = torch.rand(2,2) + 1j*torch.rand(2,2)
a = a+a.T.conj()
op = xitorch.LinearOperator.m(a)
linalg.symeig(op)
```

**Expected behavior**
Complex hermitian operators are recognized as such.
**Systems:**
 - Python version: 3.88
 - PyTorch version: 1.9
 - xitorch version: 0.2.0

**Comment by mfkasim1** [comment]
Hi @JonathanSchmidt1, thanks for opening the issue!
xitorch 0.2 does not support and tested on complex tensors, but I have added some support in the latest update (I believe symeig should work for complex now).
Could you give it a try with the github version?

**Comment by JonathanSchmidt1** [comment]
Installing from source (0.3) fixes it already. Thank you very much for the quick response and the great library.
